export const DEFAULT_ROOT = 'https://app.deckflow.com/v1';
export const DEFAULT_TIMEOUT = 300;
export const DEFAULT_POLL_INTERVAL = 2000;
export const DEFAULT_CHUNK_SIZE = 10 * 1024 * 1024;
/** When creating a task with files under this total size, attach them inline as `files` instead of async upload + `fileIds`. */
export const INLINE_TASK_FILES_MAX_BYTES = 10 * 1024 * 1024;

export const DECK_TASK_TYPES = ['pdf.pdfParse', 'pptx.parse', 'docx.parseTextAndImage', 'keynote.parseTextAndImage', 'html.getByURL', 'parse.convert'] as const;

export type DeckTaskType = (typeof DECK_TASK_TYPES)[number];
export type DeckTaskStatus = 'pending' | 'running' | 'completed' | 'failed';

export type MetadataValue =
  | string
  | number
  | boolean
  | null
  | MetadataValue[]
  | { [key: string]: MetadataValue };

export interface DeckTask<T extends DeckTaskType = DeckTaskType> {
  /** Task id generated by the backend. */
  id: string;
  /** Space/workspace id owning this task. */
  spaceId: string;
  /** Task type. */
  type: T;
  /** Current task status. */
  status: DeckTaskStatus;
  /** Ordered input file ids. */
  fileIds?: (string[]) | undefined;
  /** Task display name. */
  name?: (string) | undefined;
  /** Task parameters. */
  params?: (Record<string, unknown>) | undefined;
  /** Optional preview payload. */
  preview?: (unknown) | undefined;
  /** Task result payload. Prefer `tasks.down(taskId)` — detail responses no longer include results. */
  result?: (unknown | null) | undefined;
  /** Error message for failed tasks. */
  error?: (string | null) | undefined;
  /** ISO create timestamp. */
  createdAt?: (string) | undefined;
  /** ISO update timestamp. */
  updatedAt?: (string) | undefined;
}

export interface AuthUuidStorage {
  get(): string | null | undefined | Promise<string | null | undefined>;
  set(value: string): void | Promise<void>;
}

export interface CreateDeckOptions {
  /** API root address. Defaults to https://app.deckflow.com/v1. */
  root?: (string) | undefined;
  /** User auth token sent as X-Auth-Token. */
  token?: (string) | undefined;
  /** API key sent as Authorization: Bearer {apiKey}. */
  apiKey?: (string) | undefined;
  /** Default space id used by task and upload calls. When omitted, resolved from GET /user. */
  spaceId?: (string) | undefined;
  /** Explicit client UUID (UUID v4) sent as X-Auth-UUID. Skips automatic persistence. */
  authUuid?: (string) | undefined;
  /** Custom UUID storage for SSR, tests, or embedded integrations. */
  authUuidStorage?: (AuthUuidStorage) | undefined;
  /**
   * Called once after a 401 when a user token is present. Returned token is saved and the request is
   * retried. If omitted or refresh fails, the request fails unless allowGuestFallback is true.
   */
  onUnauthorized?: (() => Promise<{ token: string; spaceId?: string | undefined } | string>) | undefined;
  /** Permit a failed login to fall back to guest. Defaults to true in Node, false in /browser. */
  allowGuestFallback?: (boolean) | undefined;
  /** Retry POSTs on transient network/server failures. Defaults to true in Node, false in /browser. */
  retryMutations?: (boolean) | undefined;
  /** Called once after a 402 response; request is retried after this resolves. */
  onPaymentRequired?: (() => Promise<void>) | undefined;
}

/** Current user profile returned by GET /user. */
export interface UserSelf {
  id: string;
}

export interface CreateTaskParams<T extends DeckTaskType = DeckTaskType> {
  /** Stops client-side upload/submission; does not cancel an already-created cloud task. */
  signal?: (AbortSignal) | undefined;
  /** Space/workspace id. Falls back to createDeck({ spaceId }) or user.self id. */
  spaceId?: (string) | undefined;
  /** Ordered input file ids. Required for file-based parse tasks. */
  fileIds?: (string[]) | undefined;
  /**
   * Local files for the task. When total size is under {@link INLINE_TASK_FILES_MAX_BYTES}
   * and no `fileIds` are also provided, they are sent inline on task creation as `files`.
   * Otherwise they are uploaded first and the resulting ids are appended after `fileIds`.
   */
  files?: (TaskUploadInput[]) | undefined;
  /** Task type. */
  type: T;
  /** Optional task display name. */
  name?: (string) | undefined;
  /** Task parameters determined by type. */
  params?: (Record<string, unknown>) | undefined;
  /** Default upload options applied to files. Per-file options override these values. */
  upload?: (TaskUploadOptions) | undefined;
}

export interface WaitForTaskOptions {
  /** Space containing this task. Defaults to the client's space. */
  spaceId?: (string) | undefined;
  /** Stops waiting; does not cancel the cloud task. */
  signal?: (AbortSignal) | undefined;
  /** Timeout in seconds. Defaults to 300. */
  timeout?: (number) | undefined;
  /** Use Server-Sent Events first, then fall back to polling. Defaults to true. */
  useEventStream?: (boolean) | undefined;
  /** Called whenever a task update is received. */
  onProgress?: ((task: DeckTask) => void) | undefined;
  /** Poll interval in milliseconds when polling is used. */
  pollInterval?: (number) | undefined;
}

export interface TaskDownloadOptions {
  spaceId?: (string) | undefined;
  signal?: (AbortSignal) | undefined;
}

export interface SubscribeTaskHandlers<T extends DeckTaskType = DeckTaskType> {
  spaceId?: (string) | undefined;
  signal?: (AbortSignal) | undefined;
  /** Called for each task update. */
  onUpdate: (task: DeckTask<T>) => void;
  /** Called when the stream or parser fails. */
  onError?: ((error: Error) => void) | undefined;
}

export type UploadPlatform = 'oss' | 'local';

export interface AuthInfo {
  /** Upload URL. */
  url: string;
  /** Headers required by the storage provider. */
  headers: Record<string, string>;
  /** Optional Authorization header returned by the backend. */
  Authorization?: (string) | undefined;
}

export interface PartAuth {
  /** Part upload URL. */
  url: string;
  /** Headers required by the storage provider. */
  headers: Record<string, string>;
  /** Optional Authorization header returned by the backend. */
  Authorization?: (string) | undefined;
}

export interface UploadAuthResponse {
  /** File id to use in task fileIds. */
  id: string;
  /** Storage key. */
  key: string;
  /** File hash. */
  hash: string;
  /** Storage provider. */
  platform: UploadPlatform;
  /** Whether multipart upload is required. */
  multipart: boolean;
  /** Single upload or multipart completion auth. */
  auth?: (AuthInfo) | undefined;
  /** Multipart upload id. */
  multipartUploadId?: (string) | undefined;
  /** Multipart part size in bytes. */
  multipartPartSize?: (number) | undefined;
  /** Multipart part upload auth list. */
  multipartPartAuths?: (PartAuth[]) | undefined;
}

export interface PartResult {
  /** 1-based part number. */
  partNumber: number;
  /** ETag returned by OSS-style storage. */
  eTag?: (string) | undefined;
  /** Hash returned by local storage. */
  hash?: (string) | undefined;
}

export interface RequestUploadParams {
  signal?: (AbortSignal) | undefined;
  /** Space/workspace id. Falls back to createDeck({ spaceId }). */
  spaceId?: (string) | undefined;
  /** File name. */
  name: string;
  /** File byte size. */
  bytes: number;
  /** File MD5 hash. */
  hash: string;
  /** Desired chunk size in bytes. */
  chunkSize?: (number) | undefined;
}

export type UploadInput = string | Uint8Array | ArrayBuffer | Blob;

export interface UploadOptions {
  signal?: (AbortSignal) | undefined;
  /** Space/workspace id. Falls back to createDeck({ spaceId }). */
  spaceId?: (string) | undefined;
  /** File name. Required for binary inputs that do not carry a name. */
  name?: (string) | undefined;
  /** File MD5 hash. Calculated automatically when omitted. */
  hash?: (string) | undefined;
  /** Desired chunk size in bytes. */
  chunkSize?: (number) | undefined;
  /** Upload progress from 0 to 1. */
  onProgress?: ((percentage: number) => void) | undefined;
}

export type TaskUploadOptions = Omit<UploadOptions, 'spaceId'>;

export type TaskUploadInput =
  | UploadInput
  | ({
      /** File-like value, Node.js path, or binary data to upload. Paths are Node.js-only. */
      input: UploadInput;
    } & TaskUploadOptions);

/** Normalized local file ready for inline task creation or async upload. */
export interface PreparedUpload {
  name: string;
  bytes: number;
  hash: string;
  data: Uint8Array | Blob;
  chunkSize: number;
}

export interface FileUploadResult {
  /** File id to use in task fileIds. */
  id: string;
  /** File name. */
  name: string;
  /** Storage key. */
  key?: (string) | undefined;
  /** File byte size. */
  bytes: number;
  /** File MD5 hash. */
  hash: string;
}


export type TaskDownResult<T extends DeckTaskType = DeckTaskType> = unknown;
