export const DEFAULT_ROOT = 'https://app.deckflow.com/v1';
export const DEFAULT_TIMEOUT = 300;
export const DEFAULT_POLL_INTERVAL = 2000;
export const DEFAULT_CHUNK_SIZE = 10 * 1024 * 1024;

export const DECK_TASK_TYPES = [
  'file.compress',
  'image.ocr',
  'pptx.split',
  'pptx.join',
  'pptx.getFontInfo',
  'pptx.getTextShapes',
  'pptx.embedFonts',
  'convertor.ppt2image',
  'convertor.ppt2pptx',
  'convertor.ppt2pdf',
  'convertor.doc2pdf',
  'convertor.ppt2video',
  'convertor.pdf2image',
  'convertor.keynote2image',
  'convertor.keynote2html',
  'convertor.keynote2pdf',
  'convertor.html2png',
  'convertor.markdown2png',
  'convertor.html2pptx',
  'html.buildPlayer',
  'video.compress',
  'image.convertWebp',
  'image.resize',
  'generation',
  'translation',
  'revamp',
] as const;

export type DeckTaskType = (typeof DECK_TASK_TYPES)[number];
export type DeckTaskStatus = 'pending' | 'running' | 'completed' | 'failed';

export interface FileResult {
  /** File storage key or relative path returned by the backend. */
  key?: string;
  /** Public or signed URL returned by the backend when available. */
  url?: string;
  /** File name returned by the backend when available. */
  name?: string;
  /** File byte size. */
  bytes?: number;
  /** File content hash. */
  hash?: string;
  [key: string]: unknown;
}

export interface DeckTask<T extends DeckTaskType = DeckTaskType> {
  /** Task id generated by the backend. */
  id: string;
  /** Space/workspace id owning this task. */
  spaceId: string;
  /** Task type. */
  type: T;
  /** Current task status. */
  status: DeckTaskStatus;
  /** Ordered input file ids. */
  fileIds?: string[];
  /** Task display name. */
  name?: string;
  /** Task parameters. */
  params?: DeckTaskTypeParams[T];
  /** Optional preview payload. */
  preview?: DeckTaskTypePreview[T];
  /** Optional task result payload. */
  result?: DeckTaskTypeResult[T];
  /** Error message for failed tasks. */
  error?: string | null;
  /** ISO create timestamp. */
  createdAt?: string;
  /** ISO update timestamp. */
  updatedAt?: string;
  [key: string]: unknown;
}

export interface TaskListResponse<T extends DeckTaskType = DeckTaskType> {
  /** Tasks in the requested page. */
  tasks: DeckTask<T>[];
  /** Total matching task count when the backend returns it. */
  total?: number;
}

export interface CreateDeckOptions {
  /** API root address. Defaults to https://app.deckflow.com/v1. */
  root?: string;
  /** User auth token sent as X-Auth-Token. */
  token?: string;
  /** API key sent as Authorization: Bearer {apiKey}. */
  apiKey?: string;
  /** Default space id used by task and upload calls. */
  spaceId?: string;
  /** Called once after a 401 response; returned token is saved and request is retried. */
  onUnauthorized?: () => Promise<{ token: string; spaceId?: string } | string>;
  /** Called once after a 402 response; request is retried after this resolves. */
  onPaymentRequired?: () => Promise<void>;
}

export interface CreateTaskParams<T extends DeckTaskType = DeckTaskType> {
  /** Space/workspace id. Falls back to createDeck({ spaceId }). */
  spaceId?: string;
  /** Ordered input file ids. Required for most tasks except generation/html.buildPlayer. */
  fileIds?: string[];
  /** Task type. */
  type: T;
  /** Optional task display name. */
  name?: string;
  /** Task parameters determined by type. */
  params?: DeckTaskTypeParams[T];
}

export interface TaskShortcutParams<T extends DeckTaskType> extends Omit<CreateTaskParams<T>, 'type'> {}

export interface ListTasksParams<T extends DeckTaskType = DeckTaskType> {
  /** Space/workspace id. Falls back to createDeck({ spaceId }). */
  spaceId?: string;
  /** Optional task type filter. */
  type?: T;
  /** Start index for pagination. */
  startIndex?: number;
  /** Max results for pagination. */
  maxResults?: number;
}

export interface WaitForTaskOptions {
  /** Timeout in seconds. Defaults to 300. */
  timeout?: number;
  /** Use Server-Sent Events first, then fall back to polling. Defaults to true. */
  useEventStream?: boolean;
  /** Called whenever a task update is received. */
  onProgress?: (task: DeckTask) => void;
  /** Poll interval in milliseconds when polling is used. */
  pollInterval?: number;
}

export interface SubscribeTaskHandlers<T extends DeckTaskType = DeckTaskType> {
  /** Called for each task update. */
  onUpdate: (task: DeckTask<T>) => void;
  /** Called when the stream or parser fails. */
  onError?: (error: Error) => void;
}

export type UploadPlatform = 'oss' | 'local';

export interface AuthInfo {
  /** Upload URL. */
  url: string;
  /** Headers required by the storage provider. */
  headers: Record<string, string>;
  /** Optional Authorization header returned by the backend. */
  Authorization?: string;
}

export interface PartAuth {
  /** Part upload URL. */
  url: string;
  /** Headers required by the storage provider. */
  headers: Record<string, string>;
  /** Optional Authorization header returned by the backend. */
  Authorization?: string;
}

export interface UploadAuthResponse {
  /** File id to use in task fileIds. */
  id: string;
  /** Storage key. */
  key: string;
  /** File hash. */
  hash: string;
  /** Storage provider. */
  platform: UploadPlatform;
  /** Whether multipart upload is required. */
  multipart: boolean;
  /** Single upload or multipart completion auth. */
  auth?: AuthInfo;
  /** Multipart upload id. */
  multipartUploadId?: string;
  /** Multipart part size in bytes. */
  multipartPartSize?: number;
  /** Multipart part upload auth list. */
  multipartPartAuths?: PartAuth[];
}

export interface PartResult {
  /** 1-based part number. */
  partNumber: number;
  /** ETag returned by OSS-style storage. */
  eTag?: string;
  /** Hash returned by local storage. */
  hash?: string;
}

export interface RequestUploadParams {
  /** Space/workspace id. Falls back to createDeck({ spaceId }). */
  spaceId?: string;
  /** File name. */
  name: string;
  /** File byte size. */
  bytes: number;
  /** File MD5 hash. */
  hash: string;
  /** Desired chunk size in bytes. */
  chunkSize?: number;
}

export type UploadInput = string | Uint8Array | ArrayBuffer | Blob;

export interface UploadOptions {
  /** Space/workspace id. Falls back to createDeck({ spaceId }). */
  spaceId?: string;
  /** File name. Required for binary inputs that do not carry a name. */
  name?: string;
  /** File MD5 hash. Required in browser environments when SDK cannot calculate MD5. */
  hash?: string;
  /** Desired chunk size in bytes. */
  chunkSize?: number;
  /** Upload progress from 0 to 1. */
  onProgress?: (percentage: number) => void;
}

export interface FileUploadResult {
  /** File id to use in task fileIds. */
  id: string;
  /** File name. */
  name: string;
  /** Storage key. */
  key?: string;
  /** File byte size. */
  bytes: number;
  /** File MD5 hash. */
  hash: string;
}

export interface FileCompressParams {
  /** Optional target storage path. */
  target?: string;
}

export type OcrLanguage =
  | 'ar'
  | 'bg'
  | 'cs'
  | 'da'
  | 'de'
  | 'el'
  | 'en'
  | 'es'
  | 'et'
  | 'fi'
  | 'fr'
  | 'hu'
  | 'id'
  | 'it'
  | 'ja'
  | 'ko'
  | 'lt'
  | 'lv'
  | 'nb'
  | 'nl'
  | 'pl'
  | 'pt'
  | 'ro'
  | 'ru'
  | 'sk'
  | 'sl'
  | 'sv'
  | 'tr'
  | 'uk'
  | 'zh-hans'
  | 'zh-hant'
  | 'ara'
  | 'bul'
  | 'ces'
  | 'dan'
  | 'deu'
  | 'grek'
  | 'eng'
  | 'spa'
  | 'est'
  | 'fin'
  | 'fra'
  | 'hun'
  | 'ind'
  | 'ita'
  | 'jpn'
  | 'kor'
  | 'lit'
  | 'lav'
  | 'nor'
  | 'nld'
  | 'pol'
  | 'por'
  | 'ron'
  | 'rus'
  | 'slk'
  | 'slv'
  | 'swe'
  | 'tur'
  | 'ukr'
  | 'chi_sim'
  | 'chi_tra';

export interface ImageOcrParams {
  /** OCR language code. */
  language: OcrLanguage;
}

export interface PptxSplitParams {
  /** Slide indexes to split. */
  indexes?: number[];
  /** Allowed output size. */
  allowSize?: number;
  /** PPT id in backend systems that provide one. */
  pptId?: string;
  /** Version ids to split. */
  versionIds?: string[];
  /** Replacement file map. */
  replaceFiles?: Record<string, unknown>;
}

export interface PptxJoinParams {
  /** Hidden slide flags aligned with input files. */
  hiddens?: boolean[];
  /** Contact id to preserve or write. */
  contactId?: string;
  /** Section metadata. */
  sections?: unknown[];
  /** Changed layout map. */
  changedLayoutMap?: Record<string, unknown>;
  /** Whether to auto resize slides. */
  autoResize?: boolean;
}

export interface PptxGetFontInfoParams {
  /** Reserved for future backend options. */
  [key: string]: unknown;
}

export interface PptxGetTextShapesParams {
  /** Whether returned shapes include child shapes. */
  hasChildren?: boolean;
  /** Page numbers to inspect. */
  pickPages?: number[];
  /** Image filter by area ratio from 0 to 1. */
  imageFilter?: number;
  /** Whether duplicate shape ids should be fixed. */
  needFixDuplicatedShapeId?: boolean;
  /** Include layout shapes. */
  includeLayout?: boolean;
  /** Include master shapes. */
  includeMaster?: boolean;
  /** Include speaker notes. */
  includeNotes?: boolean;
  /** Ignore empty text shapes. */
  ignoreEmptyText?: boolean;
  /** Return only brief shape information. */
  onlyBrief?: boolean;
}

export interface PptxEmbedFontsParams {
  /** Font family names to embed into the PPTX. */
  usedFonts: string[];
}

export interface ConvertPptToImageParams {
  /** Output image width/resolution. */
  resolution?: number;
  /** Output image format. */
  format?: 'png' | 'jpg';
}

export interface ConvertHtmlToPngParams {
  /** Render scale. */
  scale?: number;
  /** Capture the full page. */
  fullPage?: boolean;
  /** Inline HTML content. Ignored when fileIds are used. */
  html?: string;
  /** Viewport width. */
  width?: number;
  /** Viewport height. */
  height?: number;
}

export interface ConvertMarkdownToPngParams {
  /** Render scale. */
  scale?: number;
  /** Theme name. */
  theme?: 'light' | 'dark';
  /** Page width. */
  pageWidth?: number;
  /** Inline markdown content. Ignored when fileIds are used. */
  markdown?: string;
}

export interface ConvertHtmlToPptxParams {
  /** Whether to embed fonts in the output PPTX. */
  needEmbedFonts?: boolean;
  /** Inline HTML content. Ignored when fileIds are used. */
  html?: string;
  /** Slide width. */
  width?: number;
  /** Slide height. */
  height?: number;
}

export interface HtmlBuildPlayerContent {
  /** OSS/storage key for this content page. */
  key?: string;
  /** Inline HTML for this content page. */
  html?: string;
}

export interface HtmlBuildPlayerParams {
  /** HTML pages/segments. Each item should provide either key or html. */
  contents: HtmlBuildPlayerContent[];
  /** Player page width. */
  pageWidth: number;
  /** Player page height. */
  pageHeight: number;
  /** Player title. */
  title: string;
  /** Player description. */
  description: string;
  /** Brand mark position. */
  brandMarkPosition: 'none' | 'leftTop' | 'leftBottom' | 'rightTop' | 'rightBottom';
}

export interface ImageResizeParams {
  /** Maximum width. Either maxWidth or maxHeight is required by the backend. */
  maxWidth?: number;
  /** Maximum height. Either maxWidth or maxHeight is required by the backend. */
  maxHeight?: number;
  /** Optional target storage path. */
  target?: string;
}

export interface GenerationParams {
  /** User input text. */
  inputText?: string;
  /** Whether to enable search. */
  enableSearch?: boolean;
  /** Whether to use an advanced model. */
  advancedModel?: boolean;
  /** Whether to enable fast mode. */
  fastMode?: boolean;
  /** Content generation intent. */
  intent?: string;
  /** Target audience. */
  audience?: string;
  /** Expected page count. */
  pageCount?: number;
  /** Document author. */
  author?: string;
}

export interface TranslationParams {
  /** Translation model. */
  model: 'Standard' | 'Pro';
  /** Source language. */
  from: string;
  /** Target language. */
  to: string;
  /** Whether to use glossary. */
  useGlossary: boolean;
  /** Whether to translate images inside the document. */
  imageTranslate: boolean;
}

export interface RevampParams {
  /** Output language. */
  lang?: string;
}

export interface DeckTaskTypeParams {
  'file.compress': FileCompressParams;
  'image.ocr': ImageOcrParams;
  'pptx.split': PptxSplitParams;
  'pptx.join': PptxJoinParams;
  'pptx.getFontInfo': PptxGetFontInfoParams;
  'pptx.getTextShapes': PptxGetTextShapesParams;
  'pptx.embedFonts': PptxEmbedFontsParams;
  'convertor.ppt2image': ConvertPptToImageParams;
  'convertor.ppt2pptx': Record<string, unknown>;
  'convertor.ppt2pdf': Record<string, unknown>;
  'convertor.doc2pdf': Record<string, unknown>;
  'convertor.ppt2video': Record<string, unknown>;
  'convertor.pdf2image': Record<string, unknown>;
  'convertor.keynote2image': Record<string, unknown>;
  'convertor.keynote2html': Record<string, unknown>;
  'convertor.keynote2pdf': Record<string, unknown>;
  'convertor.html2png': ConvertHtmlToPngParams;
  'convertor.markdown2png': ConvertMarkdownToPngParams;
  'convertor.html2pptx': ConvertHtmlToPptxParams;
  'html.buildPlayer': HtmlBuildPlayerParams;
  'video.compress': Record<string, unknown>;
  'image.convertWebp': Record<string, unknown>;
  'image.resize': ImageResizeParams;
  generation: GenerationParams;
  translation: TranslationParams;
  revamp: RevampParams;
}

export interface DeckTaskTypeResult {
  'file.compress': unknown;
  'image.ocr': unknown;
  'pptx.split': unknown;
  'pptx.join': unknown;
  'pptx.getFontInfo': unknown;
  'pptx.getTextShapes': unknown;
  'pptx.embedFonts': unknown;
  'convertor.ppt2image': unknown;
  'convertor.ppt2pptx': unknown;
  'convertor.ppt2pdf': unknown;
  'convertor.doc2pdf': unknown;
  'convertor.ppt2video': unknown;
  'convertor.pdf2image': unknown;
  'convertor.keynote2image': unknown;
  'convertor.keynote2html': unknown;
  'convertor.keynote2pdf': unknown;
  'convertor.html2png': unknown;
  'convertor.markdown2png': unknown;
  'convertor.html2pptx': unknown;
  'html.buildPlayer': unknown;
  'video.compress': unknown;
  'image.convertWebp': unknown;
  'image.resize': unknown;
  generation: Required<{ image?: FileResult; pptx?: FileResult; html?: FileResult }>;
  translation: FileResult;
  revamp: Required<{ image?: FileResult; pptx?: FileResult; html?: FileResult }>;
}

export interface DeckTaskTypePreview {
  'file.compress': { bytes: number };
  'pptx.split': { fileNumber: number };
  'pptx.join': { bytes: number };
  'convertor.html2pptx': FileResult[];
  'video.compress': { bytes: number };
  'image.resize': { bytes: number };
  generation: { previewURL?: string };
  translation: { previewURL?: string; before: FileResult[]; after: FileResult[] };
  revamp: { previewURL?: string; before: FileResult[] };
  'image.ocr': unknown;
  'pptx.getFontInfo': unknown;
  'pptx.getTextShapes': unknown;
  'pptx.embedFonts': unknown;
  'convertor.ppt2image': unknown;
  'convertor.ppt2pptx': unknown;
  'convertor.ppt2pdf': unknown;
  'convertor.doc2pdf': unknown;
  'convertor.ppt2video': unknown;
  'convertor.pdf2image': unknown;
  'convertor.keynote2image': unknown;
  'convertor.keynote2html': unknown;
  'convertor.keynote2pdf': unknown;
  'convertor.html2png': unknown;
  'convertor.markdown2png': unknown;
  'html.buildPlayer': unknown;
  'image.convertWebp': unknown;
}
